config/routes.rb
Rails.application.routes.draw do
root "patients#index"

resources :doctors
  resources :patients do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
has_many :appointments, dependent: :destroy
has_many :patients, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
has_many :appointments, dependent: :destroy
has_many :doctors, through: :appointments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_patient

  def index
    @doctors = @doctor.appointments.where(date: 'teacher')
    # @tas = @doctor.appointments.where(role: 'ta')
    @patients = @doctor.appointments.where(role: 'student')
  end

  def new
    @appointment = @doctor.appointments.new
  end

  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to patient_appointments_path(@doctor)
    else
      render :new
    end
  end

  def destroy
    @appointment = @doctor.appointments.find(params[:id])
    @appointment.destroy
    redirect_to patient_appointments_path(@doctor)
  end

 private
   def set_patient
     @doctor = Patient.find(params[:patient_id]) 
   end

   def appointment_params
     params.require(:appointment).permit(:date, :doctor_id)
   end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name)
    end
  end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :destroy]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new

  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to patients_path
    else
      render :new
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<%= link_to 'Add Doctor', new_doctor_path %>
<hr />
<h2><%= @doctors.length <= 0 ? "No Doctors" : "" %></h2> 
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Add Doctor</h1>
<%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Doctor Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<hr />
<br />
<%= link_to 'Appointments', patient_appointments_path(@doctor), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to "Delete Doctor", @doctor, method: :delete, class: "ui red button inverted" %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
  <div <button class="fluid ui button"></button>


      <%= link_to 'Doctors', doctors_path %> |
  
      <%= link_to 'Add Doctor', new_doctor_path %> |
    
      <%= link_to 'Patients', patients_path %> |
   
      <%= link_to 'Add Patient', new_patient_path %>
    </div>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= yield %>
  </div>
</body>
</html>

app/views/patients/index.html.erb
<h1>Patient</h1>
<%= link_to 'Add Patient', new_patient_path %>
<hr />
<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to patient.full_name, patient %>
    </li>
<% end %>
</ul>

app/views/patients/new.html.erb
<h1>Add Patient</h1>
<%= form_with(model: @patients, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/patients/show.html.erb
<h1><%= @patient.full_name %></h1>
<hr />
<h2>Patient</h2>
<ul>
  <% @doctor.patients.each do |patient| %>
    <li>
      <%= link_to patient.name, patient %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to 'Delete Patient', @patient, method: :delete, class: "ui red button inverted" %>